import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getFirestore, doc, setDoc, onSnapshot } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBF87jtpyOS6exnNMH3PPc0XND8df2I7TU",authDomain:"clickfocusmaster.firebaseapp.com",projectId:"clickfocusmaster",storageBucket:"clickfocusmaster.firebasestorage.app",messagingSenderId:"891874911950",appId:"1:891874911950:web:43ac8e66561f6a8e70d29f"};
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app);let focusRef=null,timerInterval=null,totalSeconds=0,unsubscribeUser=null;
const $=id=>document.getElementById(id);function render(sec){sec=Math.max(0,Math.floor(sec));$('timer').textContent=`${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;$('progressBar').style.width=totalSeconds?`${Math.min(100,(1-sec/totalSeconds)*100)}%`:'0%';}
function startTimer(end){clearInterval(timerInterval);const tick=async()=>{const left=Math.ceil((end-Date.now())/1000);if(left<=0){clearInterval(timerInterval);render(0);$('status').textContent='הסתיים ✅';$('status').className='status done';$('message').textContent='כל הכבוד! סשן הפוקוס הושלם.';await setDoc(focusRef,{active:false,remainingTime:0,endTime:0},{merge:true});return}render(left)};tick();timerInterval=setInterval(tick,1000)}
function bindUser(user){ if(unsubscribeUser) unsubscribeUser(); focusRef=doc(db,'users',user.uid); unsubscribeUser=onSnapshot(focusRef,s=>{if(!s.exists())return;const d=s.data();if(d.active&&d.endTime>Date.now()){totalSeconds=(d.duration||Math.ceil((d.endTime-d.startedAt)/1000/60))*60; $('status').textContent='פעיל 🟢';$('status').className='status active';startTimer(d.endTime)}else if(!d.active){render(0);$('status').textContent='כבוי';$('status').className='status'}}); }
onAuthStateChanged(auth,user=>{ if(user) bindUser(user); else { if(unsubscribeUser) unsubscribeUser(); unsubscribeUser=null; focusRef=null; clearInterval(timerInterval); render(0); $('status').textContent='יש להתחבר'; $('message').textContent='הנתונים נשמרים בנפרד לכל משתמש.'; }});
$('useCustom').onclick=()=>{const v=Number($('customTime').value);if(v>0){$('time').value=v;$('message').textContent=`נבחרו ${v} דקות`}};
window.startFocus=async()=>{if(!focusRef){alert("יש להתחבר קודם");return;}const minutes=Number($('time').value);const start=Date.now(),end=start+minutes*60000;totalSeconds=minutes*60;$('status').textContent='פעיל 🟢';$('status').className='status active';$('message').textContent='הריכוז התחיל. בהצלחה!';await setDoc(focusRef,{active:true,duration:minutes,startedAt:start,endTime:end,remainingTime:totalSeconds},{merge:true});startTimer(end)};
window.stopFocus=async()=>{if(!focusRef)return;clearInterval(timerInterval);totalSeconds=0;render(0);$('status').textContent='כבוי';$('status').className='status';$('message').textContent='';await setDoc(focusRef,{active:false,duration:0,startedAt:0,endTime:0,remainingTime:0},{merge:true})};